[radio]
sharedmem=-1

[operator]
callsign=WF8Z
gridsquare=EM79sm

[decoders]
# Normal FT8 day
decoder=14074000 FT8
decoder=18100000 FT8
decoder=21074000 FT8
decoder=24915000 FT8
decoder=28074000 FT8
# DXpedition F/H day
decoder=14090000 FT8
decoder=18095000 FT8
decoder=21090000 FT8
decoder=24911000 FT8
decoder=28090000 FT8

[wsjtx]
temppath=C:\CWSL_DIGI\wave
binpath=C:\WSJT\wsjtx\bin

[reporting]
pskreporter=true
rbn=true
aggregatorport=2215
