[radio]
sharedmem=-1

[operator]
callsign=WF8Z
gridsquare=EM79sm

[decoders]
# Bouvet night - low bands (3Y0K F/H freqs)
decoder=3567000 FT8
decoder=7090000 FT8
decoder=10131000 FT8
decoder=14090000 FT8

[wsjtx]
temppath=C:\CWSL_DIGI\wave
binpath=C:\WSJT\wsjtx\bin

[reporting]
pskreporter=true
rbn=true
aggregatorport=2215
