[radio]
sharedmem=-1

[operator]
callsign=WF8Z
gridsquare=EM79sm

[decoders]
# Normal FT8 day
decoder=14074000 FT8
decoder=18100000 FT8
decoder=21074000 FT8
decoder=24915000 FT8
decoder=28074000 FT8
# CY0S Sable Island F/H day (20/17/15/12/10m)
decoder=14091000 FT8
decoder=18091000 FT8
decoder=21091000 FT8
decoder=24911000 FT8
decoder=28091000 FT8

[wsjtx]
temppath=C:\CWSL_DIGI\wave
binpath=C:\WSJT\wsjtx\bin

[reporting]
pskreporter=true
rbn=true
aggregatorport=2215
