[radio]
sharedmem=2

[operator]
callsign=WF8Z
gridsquare=EM79sm

[decoders]
# 10m
#decoder=28180000 FT4
#decoder=28074000 FT8
# 12m
#decoder=24919000 FT4
#decoder=24915000 FT8
# 15m
#decoder=21140000 FT4
#decoder=21074000 FT8
# 17m
#decoder=18104000 FT4
#decoder=18100000 FT8
# 20m
#decoder=14080000 FT4
decoder=14074000 FT8
# 30m
#decoder=10140000 FT4
#decoder=10136000 FT8
# 40m
decoder=7074000 FT8
#decoder=7047500 FT4
# 80m
#decoder=3575000 FT4
#decoder=3573000 FT8

[wsjtx]
temppath=C:\CWSL_DIGI\wave
binpath=C:\WSJT\wsjtx\bin

[reporting]
pskreporter=false
rbn=false
aggregatorport=2215

[logging]
#loglevel=8
#logfile=C:\CWSL_DIGI\console_log.txt
#decodesfile=C:\CWSL_DIGI\decode_log.txt
