@echo off
REM ============================================================================
REM  Skimmer Setup Script - CW Skimmer Server + CWSL_Tee + CWSL_DIGI
REM  For Red Pitaya STEMlab 125-14 (rp-f09804, 192.168.1.54)
REM  Run as Administrator!
REM ============================================================================

setlocal

REM --- Configuration ---
set SHARE=\\192.168.1.101\motorola
set SKIMSRV_DIR=C:\Program Files (x86)\Afreet\SkimSrv
set CWSL_DIGI_DIR=C:\CWSL_DIGI
set WSJTX_BIN=C:\WSJT\wsjtx\bin
set CALLSIGN=WF8Z
set GRID=EM79sm
set PITAYA_IP=192.168.1.54
set HERMESINTF_DLL=HermesIntf

REM --- Check for admin ---
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo ERROR: This script must be run as Administrator!
    echo Right-click and select "Run as administrator"
    pause
    exit /b 1
)

echo ============================================================================
echo  Skimmer Setup Script
echo  Callsign: %CALLSIGN%  Grid: %GRID%
echo  Pitaya: %PITAYA_IP%
echo ============================================================================
echo.

REM --- Step 1: Install IPP70 (Intel Primitives) ---
echo [1/6] Installing Intel IPP70 libraries to SysWOW64...
if not exist "%SHARE%\cwsl_tee\CWSL-master\bin\IPP70\" (
    echo ERROR: IPP70 folder not found on share!
    pause
    exit /b 1
)
xcopy "%SHARE%\cwsl_tee\CWSL-master\bin\IPP70\*" "C:\Windows\SysWOW64\" /D /Y >nul 2>&1
echo   Done.
echo.

REM --- Step 2: Install VC++ Redistributable (x86) ---
echo [2/6] Installing VC++ 2010 Redistributable (x86)...
if exist "%SHARE%\cwsl_tee\CWSL-master\bin\vcredist_x86.exe" (
    "%SHARE%\cwsl_tee\CWSL-master\bin\vcredist_x86.exe" /q /norestart
    echo   Done.
) else (
    echo   WARNING: vcredist_x86.exe not found, skipping.
)
echo.

REM --- Step 2b: Install VC++ 2022 Redistributable (x64) ---
echo [2b/6] Installing VC++ 2022 Redistributable (x64)...
if exist "%SHARE%\cwsl_digi\vc_redist.x64.exe" (
    "%SHARE%\cwsl_digi\vc_redist.x64.exe" /quiet /norestart
    echo   Done.
) else (
    echo   WARNING: vc_redist.x64.exe not found, skipping.
)
echo.

REM --- Step 3: Install CWSL_Tee into SkimSrv ---
echo [3/6] Installing CWSL_Tee into SkimSrv...
if not exist "%SKIMSRV_DIR%" (
    echo   WARNING: SkimSrv directory not found at %SKIMSRV_DIR%
    echo   Install CW Skimmer Server first, then re-run this script.
    pause
    exit /b 1
)
REM CRITICAL: Must use 2017 CWSL_Tee.dll (18,432 bytes) from CWSL.zip
REM The 2014 GoodOldStable version (17,408 bytes) does NOT create shared memory!
copy "%SHARE%\cwsl_tee\CWSL_Tee.dll" "%SKIMSRV_DIR%\" /Y >nul
echo   Copied CWSL_Tee.dll (2017 version from CWSL.zip)

REM --- Write CWSL_Tee.cfg pointing to HermesIntf ---
echo HermesIntf> "%SKIMSRV_DIR%\CWSL_Tee.cfg"
echo 8>> "%SKIMSRV_DIR%\CWSL_Tee.cfg"
echo   Wrote CWSL_Tee.cfg (HermesIntf, buffer depth 8)
echo.

REM --- Step 4: Verify HermesIntf DLL exists ---
echo [4/6] Checking for HermesIntf DLL...
if exist "%SKIMSRV_DIR%\%HERMESINTF_DLL%.dll" (
    echo   Found: %HERMESINTF_DLL%.dll
) else (
    echo   WARNING: %HERMESINTF_DLL%.dll not found in %SKIMSRV_DIR%
    echo   Download latest from: https://github.com/k3it/HermesIntf/releases
    echo   Rename to %HERMESINTF_DLL%.dll and place in %SKIMSRV_DIR%
)
echo.

REM --- Step 5: Install CWSL_DIGI ---
echo [5/6] Installing CWSL_DIGI...
if not exist "%CWSL_DIGI_DIR%" mkdir "%CWSL_DIGI_DIR%"
if not exist "%CWSL_DIGI_DIR%\wave" mkdir "%CWSL_DIGI_DIR%\wave"

copy "%SHARE%\cwsl_digi\CWSL_DIGI-main\CWSL_DIGI.exe" "%CWSL_DIGI_DIR%\" /Y >nul
copy "%SHARE%\cwsl_digi\CWSL_DIGI-main\Qt5Core.dll" "%CWSL_DIGI_DIR%\" /Y >nul
echo   Copied CWSL_DIGI.exe and Qt5Core.dll
echo   Created wave temp directory
echo.

REM --- Step 6: Write CWSL_DIGI config.ini ---
echo [6/6] Writing CWSL_DIGI config.ini...
(
echo # CWSL_DIGI config.ini - Auto-generated by setup_skimmer.bat
echo # %DATE% %TIME%
echo.
echo [radio]
echo # sharedmem: set to match CWSL_Tee receiver index in SkimSrv
echo # Try 2, 1, 0, or -1 if decoding doesn't start
echo sharedmem=2
echo.
echo [operator]
echo callsign=%CALLSIGN%
echo gridsquare=%GRID%
echo.
echo [decoders]
echo # Uncomment bands as needed. Must match bands configured in SkimSrv.
echo # 6m
echo #decoder=50323000 FT8
echo #decoder=50318000 FT4
echo # 10m
echo #decoder=28180000 FT4
echo #decoder=28074000 FT8
echo # 12m
echo #decoder=24919000 FT4
echo #decoder=24915000 FT8
echo # 15m
echo #decoder=21140000 FT4
echo #decoder=21074000 FT8
echo # 17m
echo #decoder=18104000 FT4
echo #decoder=18100000 FT8
echo # 20m
echo #decoder=14080000 FT4
echo decoder=14074000 FT8
echo # 30m
echo #decoder=10140000 FT4
echo #decoder=10136000 FT8
echo # 40m
echo decoder=7074000 FT8
echo #decoder=7047500 FT4
echo # 80m
echo #decoder=3575000 FT4
echo #decoder=3573000 FT8
echo # 160m
echo #decoder=1840000 FT8
echo #decoder=1840000 FT4
echo.
echo [wsjtx]
echo temppath=%CWSL_DIGI_DIR%\wave
echo binpath=%WSJTX_BIN%
echo.
echo [reporting]
echo # Set to true when ready to report to spotting networks
echo pskreporter=false
echo rbn=false
echo aggregatorport=2215
echo.
echo [logging]
echo #loglevel=8
echo #logfile=%CWSL_DIGI_DIR%\console_log.txt
echo #decodesfile=%CWSL_DIGI_DIR%\decode_log.txt
) > "%CWSL_DIGI_DIR%\config.ini"
echo   Wrote config.ini
echo.

REM --- Summary ---
echo ============================================================================
echo  Setup Complete!
echo ============================================================================
echo.
echo  Next steps:
echo   1. Make sure HermesIntf_%PITAYA_IP%.dll (v24.1.13+) is in:
echo      %SKIMSRV_DIR%
echo      Download: https://github.com/k3it/HermesIntf/releases
echo.
echo   2. Install Intel Fortran redistributable (for CWSL_DIGI/jt9.exe):
echo      https://drive.google.com/drive/folders/1pk99ruANXTd_87oLce2L32H2V-P6dAFn
echo.
echo   3. Install WSJT-X to %WSJTX_BIN%
echo      (only jt9.exe and wsprd.exe are needed)
echo.
echo   4. Start Red Pitaya (ssh root@%PITAYA_IP%):
echo      cd /root ^&^& ./start.sh
echo.
echo   5. Start SkimSrv, select "CWSLTee on 9804" as receiver
echo.
echo   6. Start CWSL_DIGI from command prompt:
echo      cd %CWSL_DIGI_DIR% ^&^& CWSL_DIGI.exe
echo.
echo   7. Edit %CWSL_DIGI_DIR%\config.ini to enable more bands
echo      or adjust sharedmem if decoding doesn't start.
echo.
echo ============================================================================
pause
